# comarison between activation function in ANN by keras library

## 1- sigmoid function.
## 2- softplus function.
## 3- softsign function.
## 4- softmax function.
## 5- tanh function.
## 6- swish function.
## 7- exponential function.
## 8- elu function.
## 9- selu function.


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
# check the missing data after removing the all NAN.
dataset.isna().apply(pd.value_counts)

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender    Age  \
False      10000       10000    10000        10000      10000   10000  10000   

       Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
False   10000    10000          10000      10000           10000   

       EstimatedSalary  Exited  
False            10000   10000

In [5]:
dataset.drop('Geography',axis=1,inplace=True)
dataset.drop('Gender',axis=1,inplace=True)

dataset.head()

RowNumber  CustomerId   Surname  CreditScore  Age  Tenure    Balance  \
0          1    15634602  Hargrave          619   42       2       0.00   
1          2    15647311      Hill          608   41       1   83807.86   
2          3    15619304      Onio          502   42       8  159660.80   
3          4    15701354      Boni          699   39       1       0.00   
4          5    15737888  Mitchell          850   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

In [6]:
X = dataset.iloc[:, 3:11].values
y = dataset.iloc[:, 11].values

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)



In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


# 1- Sigmoid function

In [9]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)


Epoch 1/100
250/250 [==============================] - 1s 999us/step - loss: 0.6560 - accuracy: 0.7879
Epoch 2/100
250/250 [==============================] - 0s 975us/step - loss: 0.4568 - accuracy: 0.7976
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4462 - accuracy: 0.7904
Epoch 4/100
250/250 [==============================] - 0s 919us/step - loss: 0.4279 - accuracy: 0.8008
Epoch 5/100
250/250 [==============================] - 0s 955us/step - loss: 0.4207 - accuracy: 0.8053
Epoch 6/100
250/250 [==============================] - 0s 979us/step - loss: 0.4274 - accuracy: 0.8263
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4159 - accuracy: 0.8318
Epoch 8/100
250/250 [==============================] - 0s 951us/step - loss: 0.4168 - accuracy: 0.8306
Epoch 9/100
250/250 [==============================] - 0s 971us/step - loss: 0.4264 - accuracy: 0.8232
Epoch 10/100
250/250 [==============================] - 0s 947us/step - loss:

In [10]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1553,   42],
       [ 286,  119]], dtype=int64)

In [11]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  83.6 %


#  2- Softplus function

In [12]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softplus'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)


Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.8920 - accuracy: 0.2729
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4584 - accuracy: 0.7993
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4346 - accuracy: 0.8022
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4132 - accuracy: 0.8146
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4018 - accuracy: 0.8230
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4062 - accuracy: 0.8151
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3878 - accuracy: 0.8315
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3991 - accuracy: 0.8222
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3898 - accuracy: 0.8323
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3817 - accura

In [13]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1559,   36],
       [ 238,  167]], dtype=int64)

In [14]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  86.3 %


# 3-softsign function

In [15]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softsign'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.9052 - accuracy: 0.7954
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4643 - accuracy: 0.7947
Epoch 3/100
250/250 [==============================] - 0s 959us/step - loss: 0.4465 - accuracy: 0.7904
Epoch 4/100
250/250 [==============================] - 0s 963us/step - loss: 0.4441 - accuracy: 0.7870
Epoch 5/100
250/250 [==============================] - 0s 995us/step - loss: 0.4299 - accuracy: 0.7916
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4317 - accuracy: 0.7883
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4077 - accuracy: 0.7985
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4209 - accuracy: 0.7901
Epoch 9/100
250/250 [==============================] - 0s 951us/step - loss: 0.4071 - accuracy: 0.7957
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4012 

In [16]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1533,   62],
       [ 215,  190]], dtype=int64)

In [17]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  86.15 %


# 4-Softmax Function

In [18]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softmax'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 963us/step - loss: 0.6451 - accuracy: 0.1994
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4467 - accuracy: 0.2013
Epoch 3/100
250/250 [==============================] - 0s 955us/step - loss: 0.4410 - accuracy: 0.2117
Epoch 4/100
250/250 [==============================] - 0s 959us/step - loss: 0.4192 - accuracy: 0.2038
Epoch 5/100
250/250 [==============================] - 0s 963us/step - loss: 0.4187 - accuracy: 0.2016
Epoch 6/100
250/250 [==============================] - 0s 999us/step - loss: 0.3918 - accuracy: 0.1965
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4128 - accuracy: 0.2090
Epoch 8/100
250/250 [==============================] - 0s 935us/step - loss: 0.4000 - accuracy: 0.2034
Epoch 9/100
250/250 [==============================] - 0s 943us/step - loss: 0.3937 - accuracy: 0.2035
Epoch 10/100
250/250 [==============================] - 0s 939us/step - loss:

In [19]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[   0, 1595],
       [   0,  405]], dtype=int64)

In [20]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  20.25 %


# 5-tanh Function

In [21]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.9885 - accuracy: 0.7916
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4733 - accuracy: 0.7956
Epoch 3/100
250/250 [==============================] - 0s 955us/step - loss: 0.4444 - accuracy: 0.7970
Epoch 4/100
250/250 [==============================] - 0s 963us/step - loss: 0.4387 - accuracy: 0.7891
Epoch 5/100
250/250 [==============================] - 0s 967us/step - loss: 0.4247 - accuracy: 0.8014
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4245 - accuracy: 0.7941
Epoch 7/100
250/250 [==============================] - 0s 975us/step - loss: 0.4132 - accuracy: 0.8025
Epoch 8/100
250/250 [==============================] - 0s 951us/step - loss: 0.4013 - accuracy: 0.8184
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4001 - accuracy: 0.8177
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.400

In [22]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1515,   80],
       [ 201,  204]], dtype=int64)

In [23]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  85.95 %


# 6-swish Function

In [24]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'swish'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.9410 - accuracy: 0.8048
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4418 - accuracy: 0.7996
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4325 - accuracy: 0.8019
Epoch 4/100
250/250 [==============================] - 0s 995us/step - loss: 0.4219 - accuracy: 0.8086
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4152 - accuracy: 0.8111
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4117 - accuracy: 0.8076
Epoch 7/100
250/250 [==============================] - 0s 995us/step - loss: 0.4116 - accuracy: 0.8176
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4082 - accuracy: 0.8159
Epoch 9/100
250/250 [==============================] - 0s 975us/step - loss: 0.4051 - accuracy: 0.8176
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3900 - 

In [25]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1529,   66],
       [ 228,  177]], dtype=int64)

In [26]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  85.3 %


# 7-exponential Function

In [27]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'exponential'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 3.1770 - accuracy: 0.2029
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7847 - accuracy: 0.3833
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4853 - accuracy: 0.8091
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4433 - accuracy: 0.8140
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4309 - accuracy: 0.8161
Epoch 6/100
250/250 [==============================] - 0s 995us/step - loss: 0.4263 - accuracy: 0.8205
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4289 - accuracy: 0.8246
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4204 - accuracy: 0.8311
Epoch 9/100
250/250 [==============================] - 0s 995us/step - loss: 0.4276 - accuracy: 0.8245
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4220 - ac

In [28]:
#Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1554,   41],
       [ 227,  178]], dtype=int64)

In [29]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  86.6 %


# 8-elu function

In [30]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'elu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'elu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'elu'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 1.0295 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7161 - accuracy: 0.7943
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5265 - accuracy: 0.7973
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4796 - accuracy: 0.7924
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4666 - accuracy: 0.7942
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4573 - accuracy: 0.8006
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4562 - accuracy: 0.7973
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4683 - accuracy: 0.7952
Epoch 9/100
250/250 [==============================] - 0s 995us/step - loss: 0.4666 - accuracy: 0.8033
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4785 - accu

In [31]:
#Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1568,   27],
       [ 301,  104]], dtype=int64)

In [32]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  83.6 %


# 9- selu function

In [33]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'selu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'selu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'selu'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.7987 - accuracy: 0.8044
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4659 - accuracy: 0.7969
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4550 - accuracy: 0.7986
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4507 - accuracy: 0.7933
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4597 - accuracy: 0.7939
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4584 - accuracy: 0.7952
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4381 - accuracy: 0.8008
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4482 - accuracy: 0.7970
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4453 - accuracy: 0.7937
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4588 - accura

In [34]:
#Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

array([[1593,    2],
       [ 393,   12]], dtype=int64)

In [35]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  80.25 %


# the best accurcy by tanh and exponential activation function in this data